// src/components/ResponsiveNavi.svelte
<script>
import Navigator from "./Navigator.svelte";

let showNavi = false;
</script>

<div class="navi">
	<div class="mobile">
		{#if showNavi}
			<Navigator
				on:openMenu={() => {
					showNavi = true;
				}}
				on:closeMenu={() => {
					showNavi = false;
				}}
			/>
		{/if}
	</div>
	<div class="desktop">
		<Navigator />
	</div>
</div>

// src/components/ResponsiveNavi.vue
<template>
	<div class="navi">
		<div class="mobile">
			<navigator :show="isNaviVisible" @open="openMenu()" @close="closeMenu()" />
		</div>
		<div class="desktop">
			<navigator />
		</div>
	</div>
</template>
<script>
import { ref } from "vue";
import Navigator from "./Navigator.vue";

export default {
	components: { Navigator },
	setup() {
		const isNaviVisible = ref(false);
		const openMenu = () => {
			isNaviVisible.value = true;
		};

		const closeMenu = () => {
			isNaviVisible.value = false;
		};

		return {
			isNaviVisible,
			openMenu,
			closeMenu,
		};
	},
};
</script>
